[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "src/views"   # ou "." si tu veux juste exposer les templates

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
